import Landing from "@/components/Landing";
import About from "@/components/About";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Projects from "@/components/Projects";
import Work from "@/components/Work";

export default function Home() {
    return (
        <>
            <Head>
                <title>Prabhu Marappan</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-gray-100">
                <Navbar />
                <Landing />
                <About />
                <Projects />
                <Work />
            </main>
        </>
    );
}
